// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.fenghuo.model;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface sendMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fenghuo.model.sendMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string staffTel = 1;</code>
     */
    boolean hasStaffTel();
    /**
     * <code>required string staffTel = 1;</code>
     */
    java.lang.String getStaffTel();
    /**
     * <code>required string staffTel = 1;</code>
     */
    com.google.protobuf.ByteString
        getStaffTelBytes();

    /**
     * <code>required int64 orderId = 2;</code>
     */
    boolean hasOrderId();
    /**
     * <code>required int64 orderId = 2;</code>
     */
    long getOrderId();

    /**
     * <code>required string address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>required string address = 3;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>required string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.fenghuo.model.sendMsg}
   */
  public static final class sendMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.fenghuo.model.sendMsg)
      sendMsgOrBuilder {
    // Use sendMsg.newBuilder() to construct.
    private sendMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private sendMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final sendMsg defaultInstance;
    public static sendMsg getDefaultInstance() {
      return defaultInstance;
    }

    public sendMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private sendMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              staffTel_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              orderId_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_sendMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_sendMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fenghuo.model.Msg.sendMsg.class, com.fenghuo.model.Msg.sendMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<sendMsg> PARSER =
        new com.google.protobuf.AbstractParser<sendMsg>() {
      public sendMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new sendMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<sendMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STAFFTEL_FIELD_NUMBER = 1;
    private java.lang.Object staffTel_;
    /**
     * <code>required string staffTel = 1;</code>
     */
    public boolean hasStaffTel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string staffTel = 1;</code>
     */
    public java.lang.String getStaffTel() {
      java.lang.Object ref = staffTel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          staffTel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string staffTel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStaffTelBytes() {
      java.lang.Object ref = staffTel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staffTel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERID_FIELD_NUMBER = 2;
    private long orderId_;
    /**
     * <code>required int64 orderId = 2;</code>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 orderId = 2;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private java.lang.Object address_;
    /**
     * <code>required string address = 3;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string address = 3;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      staffTel_ = "";
      orderId_ = 0L;
      address_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStaffTel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStaffTelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, orderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAddressBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStaffTelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, orderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAddressBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fenghuo.model.Msg.sendMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fenghuo.model.Msg.sendMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fenghuo.model.Msg.sendMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fenghuo.model.Msg.sendMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fenghuo.model.Msg.sendMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fenghuo.model.Msg.sendMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fenghuo.model.Msg.sendMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fenghuo.model.Msg.sendMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fenghuo.model.Msg.sendMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fenghuo.model.Msg.sendMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fenghuo.model.Msg.sendMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fenghuo.model.sendMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fenghuo.model.sendMsg)
        com.fenghuo.model.Msg.sendMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_sendMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_sendMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fenghuo.model.Msg.sendMsg.class, com.fenghuo.model.Msg.sendMsg.Builder.class);
      }

      // Construct using com.fenghuo.model.Msg.sendMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        staffTel_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_sendMsg_descriptor;
      }

      public com.fenghuo.model.Msg.sendMsg getDefaultInstanceForType() {
        return com.fenghuo.model.Msg.sendMsg.getDefaultInstance();
      }

      public com.fenghuo.model.Msg.sendMsg build() {
        com.fenghuo.model.Msg.sendMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fenghuo.model.Msg.sendMsg buildPartial() {
        com.fenghuo.model.Msg.sendMsg result = new com.fenghuo.model.Msg.sendMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.staffTel_ = staffTel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fenghuo.model.Msg.sendMsg) {
          return mergeFrom((com.fenghuo.model.Msg.sendMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fenghuo.model.Msg.sendMsg other) {
        if (other == com.fenghuo.model.Msg.sendMsg.getDefaultInstance()) return this;
        if (other.hasStaffTel()) {
          bitField0_ |= 0x00000001;
          staffTel_ = other.staffTel_;
          onChanged();
        }
        if (other.hasOrderId()) {
          setOrderId(other.getOrderId());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStaffTel()) {
          
          return false;
        }
        if (!hasOrderId()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fenghuo.model.Msg.sendMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fenghuo.model.Msg.sendMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object staffTel_ = "";
      /**
       * <code>required string staffTel = 1;</code>
       */
      public boolean hasStaffTel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public java.lang.String getStaffTel() {
        java.lang.Object ref = staffTel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            staffTel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStaffTelBytes() {
        java.lang.Object ref = staffTel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staffTel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public Builder setStaffTel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        staffTel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public Builder clearStaffTel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        staffTel_ = getDefaultInstance().getStaffTel();
        onChanged();
        return this;
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public Builder setStaffTelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        staffTel_ = value;
        onChanged();
        return this;
      }

      private long orderId_ ;
      /**
       * <code>required int64 orderId = 2;</code>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 orderId = 2;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <code>required int64 orderId = 2;</code>
       */
      public Builder setOrderId(long value) {
        bitField0_ |= 0x00000002;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 orderId = 2;</code>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>required string address = 3;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string address = 3;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string address = 3;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string address = 3;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.fenghuo.model.sendMsg)
    }

    static {
      defaultInstance = new sendMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.fenghuo.model.sendMsg)
  }

  public interface balanceMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fenghuo.model.balanceMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string staffTel = 1;</code>
     */
    boolean hasStaffTel();
    /**
     * <code>required string staffTel = 1;</code>
     */
    java.lang.String getStaffTel();
    /**
     * <code>required string staffTel = 1;</code>
     */
    com.google.protobuf.ByteString
        getStaffTelBytes();

    /**
     * <code>required int64 oldOrderId = 2;</code>
     */
    boolean hasOldOrderId();
    /**
     * <code>required int64 oldOrderId = 2;</code>
     */
    long getOldOrderId();

    /**
     * <code>required int64 newOrderId = 3;</code>
     */
    boolean hasNewOrderId();
    /**
     * <code>required int64 newOrderId = 3;</code>
     */
    long getNewOrderId();

    /**
     * <code>required string address = 4;</code>
     */
    boolean hasAddress();
    /**
     * <code>required string address = 4;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>required string address = 4;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.fenghuo.model.balanceMsg}
   */
  public static final class balanceMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.fenghuo.model.balanceMsg)
      balanceMsgOrBuilder {
    // Use balanceMsg.newBuilder() to construct.
    private balanceMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private balanceMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final balanceMsg defaultInstance;
    public static balanceMsg getDefaultInstance() {
      return defaultInstance;
    }

    public balanceMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private balanceMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              staffTel_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              oldOrderId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              newOrderId_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              address_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_balanceMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_balanceMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fenghuo.model.Msg.balanceMsg.class, com.fenghuo.model.Msg.balanceMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<balanceMsg> PARSER =
        new com.google.protobuf.AbstractParser<balanceMsg>() {
      public balanceMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new balanceMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<balanceMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STAFFTEL_FIELD_NUMBER = 1;
    private java.lang.Object staffTel_;
    /**
     * <code>required string staffTel = 1;</code>
     */
    public boolean hasStaffTel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string staffTel = 1;</code>
     */
    public java.lang.String getStaffTel() {
      java.lang.Object ref = staffTel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          staffTel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string staffTel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStaffTelBytes() {
      java.lang.Object ref = staffTel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staffTel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OLDORDERID_FIELD_NUMBER = 2;
    private long oldOrderId_;
    /**
     * <code>required int64 oldOrderId = 2;</code>
     */
    public boolean hasOldOrderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 oldOrderId = 2;</code>
     */
    public long getOldOrderId() {
      return oldOrderId_;
    }

    public static final int NEWORDERID_FIELD_NUMBER = 3;
    private long newOrderId_;
    /**
     * <code>required int64 newOrderId = 3;</code>
     */
    public boolean hasNewOrderId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 newOrderId = 3;</code>
     */
    public long getNewOrderId() {
      return newOrderId_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private java.lang.Object address_;
    /**
     * <code>required string address = 4;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string address = 4;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      staffTel_ = "";
      oldOrderId_ = 0L;
      newOrderId_ = 0L;
      address_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStaffTel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOldOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStaffTelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, oldOrderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, newOrderId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAddressBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStaffTelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, oldOrderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, newOrderId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAddressBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.fenghuo.model.Msg.balanceMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.fenghuo.model.Msg.balanceMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.fenghuo.model.Msg.balanceMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fenghuo.model.balanceMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fenghuo.model.balanceMsg)
        com.fenghuo.model.Msg.balanceMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_balanceMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_balanceMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fenghuo.model.Msg.balanceMsg.class, com.fenghuo.model.Msg.balanceMsg.Builder.class);
      }

      // Construct using com.fenghuo.model.Msg.balanceMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        staffTel_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        oldOrderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        newOrderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fenghuo.model.Msg.internal_static_com_fenghuo_model_balanceMsg_descriptor;
      }

      public com.fenghuo.model.Msg.balanceMsg getDefaultInstanceForType() {
        return com.fenghuo.model.Msg.balanceMsg.getDefaultInstance();
      }

      public com.fenghuo.model.Msg.balanceMsg build() {
        com.fenghuo.model.Msg.balanceMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fenghuo.model.Msg.balanceMsg buildPartial() {
        com.fenghuo.model.Msg.balanceMsg result = new com.fenghuo.model.Msg.balanceMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.staffTel_ = staffTel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.oldOrderId_ = oldOrderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.newOrderId_ = newOrderId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fenghuo.model.Msg.balanceMsg) {
          return mergeFrom((com.fenghuo.model.Msg.balanceMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fenghuo.model.Msg.balanceMsg other) {
        if (other == com.fenghuo.model.Msg.balanceMsg.getDefaultInstance()) return this;
        if (other.hasStaffTel()) {
          bitField0_ |= 0x00000001;
          staffTel_ = other.staffTel_;
          onChanged();
        }
        if (other.hasOldOrderId()) {
          setOldOrderId(other.getOldOrderId());
        }
        if (other.hasNewOrderId()) {
          setNewOrderId(other.getNewOrderId());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000008;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStaffTel()) {
          
          return false;
        }
        if (!hasOldOrderId()) {
          
          return false;
        }
        if (!hasNewOrderId()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fenghuo.model.Msg.balanceMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fenghuo.model.Msg.balanceMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object staffTel_ = "";
      /**
       * <code>required string staffTel = 1;</code>
       */
      public boolean hasStaffTel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public java.lang.String getStaffTel() {
        java.lang.Object ref = staffTel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            staffTel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStaffTelBytes() {
        java.lang.Object ref = staffTel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staffTel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public Builder setStaffTel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        staffTel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public Builder clearStaffTel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        staffTel_ = getDefaultInstance().getStaffTel();
        onChanged();
        return this;
      }
      /**
       * <code>required string staffTel = 1;</code>
       */
      public Builder setStaffTelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        staffTel_ = value;
        onChanged();
        return this;
      }

      private long oldOrderId_ ;
      /**
       * <code>required int64 oldOrderId = 2;</code>
       */
      public boolean hasOldOrderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 oldOrderId = 2;</code>
       */
      public long getOldOrderId() {
        return oldOrderId_;
      }
      /**
       * <code>required int64 oldOrderId = 2;</code>
       */
      public Builder setOldOrderId(long value) {
        bitField0_ |= 0x00000002;
        oldOrderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 oldOrderId = 2;</code>
       */
      public Builder clearOldOrderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        oldOrderId_ = 0L;
        onChanged();
        return this;
      }

      private long newOrderId_ ;
      /**
       * <code>required int64 newOrderId = 3;</code>
       */
      public boolean hasNewOrderId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 newOrderId = 3;</code>
       */
      public long getNewOrderId() {
        return newOrderId_;
      }
      /**
       * <code>required int64 newOrderId = 3;</code>
       */
      public Builder setNewOrderId(long value) {
        bitField0_ |= 0x00000004;
        newOrderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 newOrderId = 3;</code>
       */
      public Builder clearNewOrderId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        newOrderId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>required string address = 4;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string address = 4;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string address = 4;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string address = 4;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string address = 4;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.fenghuo.model.balanceMsg)
    }

    static {
      defaultInstance = new balanceMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.fenghuo.model.balanceMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fenghuo_model_sendMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_fenghuo_model_sendMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fenghuo_model_balanceMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_fenghuo_model_balanceMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMsg.proto\022\021com.fenghuo.model\"=\n\007sendMs" +
      "g\022\020\n\010staffTel\030\001 \002(\t\022\017\n\007orderId\030\002 \002(\003\022\017\n\007" +
      "address\030\003 \002(\t\"W\n\nbalanceMsg\022\020\n\010staffTel\030" +
      "\001 \002(\t\022\022\n\noldOrderId\030\002 \002(\003\022\022\n\nnewOrderId\030" +
      "\003 \002(\003\022\017\n\007address\030\004 \002(\tB\030\n\021com.fenghuo.mo" +
      "delB\003Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_fenghuo_model_sendMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fenghuo_model_sendMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_fenghuo_model_sendMsg_descriptor,
        new java.lang.String[] { "StaffTel", "OrderId", "Address", });
    internal_static_com_fenghuo_model_balanceMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fenghuo_model_balanceMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_fenghuo_model_balanceMsg_descriptor,
        new java.lang.String[] { "StaffTel", "OldOrderId", "NewOrderId", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
